[project]
name = "fsapi"
version = "0.1.0"
description = "Simple app to convert data from the fs25 api to json formatted data"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "requests>=2.32.3",
    "setuptools==80.3.1",
    "uvicorn>=0.34.2",
    "feedparser>=6.0.10"
]
